### ISSUE TITLE
composable functions throw errors

### ISSUE THREAD

**Issue by edwardz8** [jahidanowar/nuxt3-wp-blog#3]
with the current composable file from the youtube video and the repo, i get the following error:

GET http://localhost:3000/undefined/wp-json/wp/v2/posts?page=1&per_page=20&_embed=1

404 Page not found: /undefined/wp-json/wp/v2/posts?page=1&per_page=20&_embed=1

the code wants me to format it like this:

const { data: posts } = await (await useWpApi()).getPosts(); 

but this does not work either and i get:

http://localhost:3000/undefined/wp-json/v2/posts 

is there something on the wordpress dashboard side of things that you've done that is required that i've overlooked on youtube? if so, could you provide it in the readme file?

**Comment by jahidanowar** [comment]
Have you created the .env file?

If not then create a `.env` file and add a variable like this.

```
WP_URI=YOUR_WORDPRESS_URL
```

**Comment by edwardz8** [comment]
> Have you created the .env file?
> 
> 
> 
> If not then create a `.env` file and add a variable like this.
> 
> 
> 
> ```
> 
> WP_URI=YOUR_WORDPRESS_URL
> 
> ```

yes 

https://github.com/edwardz8/nuxt3-headless 

posts actually show on initial render but then if you refresh the page they disappear without any error. same for categories and routing to a single post and single category. then errors like this are thrown:

TypeError: useWpApi(...).getPost is not a function

https://www.loom.com/share/3b0287fd34f746649ce6cb877272170d

https://www.loom.com/share/35b4158477dc45a3996d63fa70cca203

and also in the console i receive:
Unhandled error during execution of setup function 23:53:06 at <Index onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref<undefined>>

i followed your repo here: https://github.com/jahidanowar/nuxt3-demo-wp 

and i didn't run into as many issues. but for now, on initial render of each page, the posts and categories appear, however, on refreshing the page the posts and categories disappear.

**Comment by jahidanowar** [comment]
> > Have you created the .env file?
> 
> > 
> 
> > 
> 
> > 
> 
> > If not then create a `.env` file and add a variable like this.
> 
> > 
> 
> > 
> 
> > 
> 
> > ```
> 
> > 
> 
> > WP_URI=YOUR_WORDPRESS_URL
> 
> > 
> 
> > ```
> 
> 
> 
> yes 
> 
> 
> 
> https://github.com/edwardz8/nuxt3-headless 
> 
> 
> 
> posts actually show on initial render but then if you refresh the page they disappear without any error. same for categories and routing to a single post and single category. then errors like this are thrown:
> 
> 
> 
> TypeError: useWpApi(...).getPost is not a function
> 
> 
> 
> https://www.loom.com/share/3b0287fd34f746649ce6cb877272170d
> 
> 
> 
> https://www.loom.com/share/35b4158477dc45a3996d63fa70cca203
> 
> 
> 
> and also in the console i receive:
> 
> Unhandled error during execution of setup function 23:53:06 at <Index onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref<undefined>>
> 
> 
> 
> i followed your repo here: https://github.com/jahidanowar/nuxt3-demo-wp 
> 
> 
> 
> and i didn't run into as many issues. but for now, on initial render of each page, the posts and categories appear, however, on refreshing the page the posts and categories disappear.

Please check the recent commits. I was able reproduce your issue. It was type issue and I've fixed it already.
