### ISSUE TITLE
app crashes on page refresh

### ISSUE THREAD

**Issue by edwardz8** [jahidanowar/nuxt3-wp-blog#4]
neither posts nor categories load on refresh and app crashes on multiple reloads.

https://www.loom.com/share/26607beb4bfb45fe9d8e533a0c75fc08

steps to reproduce: 

1) clone repo and npm install
2) add wordpress URL to .env file
3) run code
4) try refreshing pages and watch posts and categories disappear

**Comment by jahidanowar** [comment]
I tried reproducing the issue. But It's working for me.
Check this for reference
https://sc.jahid.dev/recordings/fRVNK0RQF4tvK5X6c2tn

**Comment by jahidanowar** [comment]
> neither posts nor categories load on refresh and app crashes on multiple reloads.
> 
> https://www.loom.com/share/26607beb4bfb45fe9d8e533a0c75fc08
> 
> steps to reproduce:
> 
> 1. clone repo and npm install
> 2. add wordpress URL to .env file
> 3. run code
> 4. try refreshing pages and watch posts and categories disappear

I tried reproducing the issue. But It's working for me.
Check this for reference
https://sc.jahid.dev/recordings/fRVNK0RQF4tvK5X6c2tn

**Comment by edwardz8** [comment]
issue is resolved. something to do with my local site. the live site link works.

**Comment by edwardz8** [comment]
issue is resolved. something to do with my local site. the live site link works.
